import { useLanguage } from '@/contexts/LanguageContext';
import Navbar from '@/components/Header';
import Footer from '@/components/Footer';
// Image URLs
import HeroImage from "@/assets/images/herosection.png";
export default function PrivacyPolicy() {
    const { dir, language } = useLanguage();
    const isRTL = dir === 'rtl';

    const sections = [
        {
            number: '1.',
            title: language === 'en' ? 'Information We Collect' : 'المعلومات التي نجمعها',
            content: language === 'en'
                ? 'We collect information you provide directly (such as name, work email, and contact details), information generated by your use of the platform (such as log data and usage metrics), and information from cookies or similar technologies.'
                : 'نجمع المعلومات التي تقدمها مباشرة (مثل الاسم والبريد الإلكتروني الخاص بالعمل وتفاصيل الاتصال)، والمعلومات الناتجة عن استخدامك للمنصة (مثل بيانات السجل ومقاييس الاستخدام)، والمعلومات من ملفات تعريف الارتباط أو التقنيات المماثلة.',
        },
        {
            number: '2.',
            title: language === 'en' ? 'How We Use Information' : 'كيف نستخدم المعلومات',
            isList: true,
            items: language === 'en'
                ? [
                    'Provide, maintain, and improve our services.',
                    'Personalize your experience and deliver relevant insights.',
                    'Communicate with you about updates, support, and marketing (if opted in).',
                    'Protect against fraud, abuse, and security incidents.',
                ]
                : [
                    'تقديم خدماتنا وصيانتها وتحسينها.',
                    'تخصيص تجربتك وتقديم رؤى ذات صلة.',
                    'التواصل معك بشأن التحديثات والدعم والتسويق (إذا وافقت على ذلك).',
                    'الحماية من الاحتيال والإساءة والحوادث الأمنية.',
                ],
        },
        {
            number: '3.',
            title: language === 'en' ? 'Legal Bases (Where Applicable)' : 'الأسس القانونية (حيثما ينطبق)',
            content: language === 'en'
                ? 'We process personal data based on consent, contractual necessity, compliance with legal obligations, and legitimate interests such as securing our services.'
                : 'نعالج البيانات الشخصية بناءً على الموافقة، والضرورة التعاقدية، والامتثال للالتزامات القانونية، والمصالح المشروعة مثل تأمين خدماتنا.',
        },
        {
            number: '4.',
            title: language === 'en' ? 'Sharing & Disclosure' : 'المشاركة والإفصاح',
            content: language === 'en'
                ? 'We may share information with trusted service providers, professional advisors, and business partners who perform services on our behalf, subject to appropriate confidentiality obligations. We may also disclose information to comply with legal requirements or protect our rights.'
                : 'قد نشارك المعلومات مع مزودي الخدمات الموثوقين والمستشارين المحترفين وشركاء الأعمال الذين يؤدون خدمات نيابةً عنا، وفقاً لالتزامات السرية المناسبة. كما قد نكشف عن المعلومات للامتثال للمتطلبات القانونية أو حماية حقوقنا.',
        },
        {
            number: '5.',
            title: language === 'en' ? 'Data Retention' : 'الاحتفاظ بالبيانات',
            content: language === 'en'
                ? 'We retain personal data only as long as necessary for the purposes described in this policy, unless a longer retention period is required or permitted by law.'
                : 'نحتفظ بالبيانات الشخصية فقط طالما كان ذلك ضرورياً للأغراض الموضحة في هذه السياسة، ما لم يكن القانون يستوجب أو يسمح بفترة احتفاظ أطول.',
        },
        {
            number: '6.',
            title: language === 'en' ? 'Security' : 'الأمان',
            content: language === 'en'
                ? 'We implement reasonable administrative, technical, and organizational measures to protect your information. No method of transmission or storage is fully secure.'
                : 'نطبق تدابير إدارية وتقنية وتنظيمية معقولة لحماية معلوماتك. لا توجد طريقة نقل أو تخزين آمنة تماماً.',
        },
        {
            number: '7.',
            title: language === 'en' ? 'International Transfers' : 'النقل الدولي',
            content: language === 'en'
                ? 'Your information may be processed in countries other than your own. We take steps to ensure appropriate safeguards are in place where required.'
                : 'قد تتم معالجة معلوماتك في دول أخرى غير بلدك. نتخذ خطوات لضمان وجود ضمانات مناسبة حيثما كان ذلك مطلوباً.',
        },
        {
            number: '8.',
            title: language === 'en' ? 'Your Rights & Choices' : 'حقوقك وخياراتك',
            content: language === 'en'
                ? 'Depending on your location, you may have rights to access, correct, delete, or restrict the processing of your personal data, and to withdraw consent. You can also opt out of marketing communications at any time.'
                : 'بناءً على موقعك الجغرافي، قد يحق لك الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها أو تقييد معالجتها، وسحب موافقتك. يمكنك أيضاً إلغاء الاشتراك في الاتصالات التسويقية في أي وقت.',
        },
        {
            number: '9.',
            title: language === 'en' ? 'Cookies' : 'ملفات تعريف الارتباط',
            content: language === 'en'
                ? 'We use cookies and similar technologies to enhance functionality and analytics. You can manage cookie preferences through your browser settings.'
                : 'نستخدم ملفات تعريف الارتباط والتقنيات المماثلة لتحسين الوظائف والتحليلات. يمكنك إدارة تفضيلات ملفات تعريف الارتباط من خلال إعدادات متصفحك.',
        },
        {
            number: '10.',
            title: language === 'en' ? 'Changes to This Policy' : 'التغييرات على هذه السياسة',
            content: language === 'en'
                ? 'We may update this policy from time to time. The "Last updated" date indicates when changes were made.'
                : 'قد نقوم بتحديث هذه السياسة من وقت لآخر. يشير تاريخ "آخر تحديث" إلى وقت إجراء التغييرات.',
        },
    ];

    return (
        <div className="min-h-screen flex flex-col bg-white">
            <Navbar />

            <main className="flex-1 pt-20">
              {/* Hero */}
<div className="relative w-full pl-5 pr-8 py-24 overflow-hidden">

  {/* Background Image */}
  <div className="absolute inset-0">
    <img
      src={HeroImage}
      alt="Hero Background"
      className="w-full h-full object-cover"
    />
    {/* Dark overlay */}
    <div className="absolute inset-0 bg-blue-900/40" />
  </div>

  {/* Content */}
  <div className="relative z-10 text-center">
    {/* <p className="text-[#32a7b5] text-sm font-semibold uppercase tracking-widest mb-3">
      {language === 'en' ? 'Legal' : 'قانوني'}
    </p> */}
    <h1 className={`text-4xl md:text-6xl font-bold text-white mb-5 ${isRTL ? 'font-arabic' : 'font-display'}`}>
      {language === 'en' ? 'Privacy Policy' : 'سياسة الخصوصية'}
    </h1>
    {/* <p className={`text-white/80 text-lg text-center leading-relaxed mb-4  ${isRTL ? 'font-arabic' : 'font-body'}`}>
      {language === 'en'
        ? 'This Privacy Policy explains how Deeplenze Technologies collects, uses, discloses, and safeguards your information when you use our services.'
        : 'توضح سياسة الخصوصية هذه كيفية قيام شركة ديب لنز للتقنيات بجمع معلوماتك واستخدامها والإفصاح عنها وحمايتها عند استخدامك لخدماتنا.'}
    </p> */}
   
  </div>

</div>

                {/* Content */}
              <h1 className='text-black mx-6 my-5'>
                At Deeplenz, we are committed to protecting the privacy and security of our users, clients, and visitors. This Privacy Policy explains how Deeplenz collects, uses, stores, and protects personal and organizational information when you access our website, use our services, or interact with our products. By using the Deeplenz website or services, you agree to the practices described in this Privacy Policy.
Deeplenz may collect certain information when users visit our website, contact us, or use our services. This information may include personal details such as name, email address, phone number, company name, job title, and other information provided voluntarily through contact forms, service inquiries, or registration processes. In addition, we may collect technical information such as IP address, browser type, device information, operating system, pages visited, and interaction data to help us understand how our website and services are used.
The information collected by Deeplenz is used to provide and improve our services, respond to inquiries, deliver cybersecurity, AI, and cloud-related solutions, manage service engagements, communicate with clients, and enhance the overall user experience. We may also use collected data to improve our products, conduct analytics, monitor system performance, ensure security, and develop new services and technologies.
Deeplenz may collect information automatically through technologies such as cookies, analytics tools, and log files. Cookies help us improve website functionality, remember user preferences, analyze traffic patterns, and enhance website performance. Users may choose to disable cookies through their browser settings, although some features of the website may not function properly if cookies are disabled.
We take reasonable administrative, technical, and organizational measures to protect personal and business information against unauthorized access, misuse, alteration, or disclosure. These measures may include secure data storage, encryption, access controls, and security monitoring systems. While we strive to protect information using industry-standard practices, no method of transmission over the internet or electronic storage can be guaranteed to be completely secure.
Deeplenz may share certain information with trusted third-party service providers when necessary to deliver our services. These third parties may include cloud infrastructure providers, analytics platforms, cybersecurity tools, payment processors, or software integration partners. Such third parties are required to handle information in accordance with applicable data protection standards and only for the purposes necessary to provide the requested services.
In some cases, Deeplenz may be required to disclose information if required by law, legal process, government request, or to protect the rights, property, or safety of Deeplenz, its clients, or other users. We may also disclose information when necessary to investigate potential fraud, security incidents, or violations of applicable laws or service agreements.
Our website and services may contain links to third-party websites, platforms, or services that are not operated or controlled by Deeplenz. We are not responsible for the privacy practices or policies of such third-party services. Users are encouraged to review the privacy policies of any external websites they visit.
Deeplenz retains personal and business information only for as long as necessary to fulfill the purposes described in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements. When information is no longer required, reasonable steps will be taken to securely delete or anonymize the data.
Users may have the right, depending on applicable laws, to request access to the personal information we hold about them, request corrections, request deletion of their data, or object to certain types of data processing. Requests related to personal data may be submitted through the contact information provided on our website.
Deeplenz may update this Privacy Policy from time to time to reflect changes in legal requirements, technology, or business operations. Any updates will be published on the website, and continued use of our website or services after such updates indicates acceptance of the revised Privacy Policy.
If you have any questions regarding this Privacy Policy or how your information is handled, you may contact Deeplenz through the contact details provided on our website.
              </h1>
            </main>

            <Footer />
        </div>
    );
}